#!/usr/bin/env bash

if [ -z "$3" ]; then ARG_ERR=ERR; fi
if [ -z "$2" ]; then ARG_ERR=ERR; fi
if [ -z "$1" ]; then ARG_ERR=ERR; fi
if [ -n "$ARG_ERR" ];
then
    echo "Usage: <filename> <keygroup>.<name> <value>"
    exit
fi

filename=$1
if [ "$filename" == '--stdout' ]; then
  filename='/dev/stdout'
fi
value=$3
keygroup=$(echo "$2" | awk -F\. '{print $1}')
name=$(echo "$2" | awk -F\. '{print $2}')

echo -e "[$keygroup]\n\t$name = \"$value\"" >> $filename
