#!/usr/bin/env bash

if [ -z "$3" ]; then ARG_ERR=ERR; fi
if [ -z "$2" ]; then ARG_ERR=ERR; fi
if [ -z "$1" ]; then ARG_ERR=ERR; fi
if [ -n "$ARG_ERR" ];
then
    echo "Usage: <filename> <keygroup>.<name> <value>"
    exit
fi

filename=$1
value=$3
keygroup=$(echo "$2" | awk -F\. '{print $1}')
name=$(echo "$2" | awk -F\. '{print $2}')

grep --quiet "$keygroup" $filename 2>/dev/null
exit_code=$?
if [ $exit_code -eq 0 ]
then
  `sed -i'' -e "/\[git\]/a \
    $name = "$value"" ".github" `
else
  echo -e "[$keygroup]\n\t$name = \"$value\"" >> $filename
fi
